# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development: &default
  adapter: mysql2
  database: rebirth_development
  user: root
  pool: 5
  timeout: 5000
  host: aoi_pairwise_db
  port: 3306
  username: root
  password: 123456

production:
  adapter: <%= ENV['RAILS_DB_ADAPTER'] || 'mysql2' %>
  host: <%= ENV['RAILS_DB_HOST'] || 'aoi-pairwise-db' %>
  port: <%= ENV['RAILS_DB_PORT'] || 3306 %>
  user: <%= ENV['RAILS_DB_USERNAME'] || 'root' %>
  username: <%= ENV['RAILS_DB_USERNAME'] || 'root' %>
  password: <%= ENV['RAILS_DB_PASSWORD'] || '123456' %>
  database: <%= ENV['RAILS_DB_NAME'] || 'rebirth_production' %>
  pool: 5
  timeout: 5000

test: &test
  <<: *default
  database: pairwise_test

cucumber:
  <<: *test

