# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development: &default
  adapter: mysql2
  database: rebirth_development
  user: root
  pool: 5
  timeout: 5000
  host: aoi_pairwise_db
  port: 3306
  username: root
  password: 123456

production:
  adapter: mysql2
  database: rebirth_production
  user: root
  pool: 5
  timeout: 5000
  host: aoi-pairwise-db
  port: 3306
  username: root
  password: 123456

test: &test
  <<: *default
  database: pairwise_test

cucumber:
  <<: *test

